tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "duti"
brew "emacs-plus"
brew "fish"
brew "fzf"
brew "git"
brew "mackup"
brew "mas"
brew "node"
brew "python"
brew "ruby"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tldr"
brew "vim"
brew "wget"
cask "1password"
cask "alfred"
cask "balenaetcher"
cask "dash"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "iina"
cask "intellij-idea"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "logitech-options"
cask "postman"
cask "sonos"
cask "scroll-reverser"
cask "spotify"
cask "sublime-text"
cask "typora"
mas "Amphetamine", id: 937984704
mas "BetterSnapTool", id: 417375580
mas "Telegram", id: 747648890

